## Logistic Regression For Multiclass Classification

In [1]:
# make a prediction with a multinomial logistic regression model
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression
# define dataset
X, y = make_classification(n_samples=1000, n_features=10, n_informative=5, n_redundant=5, n_classes=3, random_state=1)

In [2]:
# define the multinomial logistic regression model For multiclass classification
model = LogisticRegression(multi_class='ovr', solver='lbfgs')

In [3]:
# Train test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [4]:
# trianing model
model.fit(X_train,y_train)

C:\Users\abhishek.anand\AppData\Roaming\Python\Python313\site-packages\sklearn\linear_model\_logistic.py:1281: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.8. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(


LogisticRegression(multi_class='ovr')

In [5]:
y_pred=model.predict(X_test)

In [6]:
model.predict_proba(X_test)

array([[9.10641007e-02, 5.88918814e-01, 3.20017086e-01],
       [7.74913438e-02, 8.83935792e-01, 3.85728639e-02],
       [6.84424719e-01, 2.03486076e-01, 1.12089205e-01],
       [1.43078246e-02, 9.01463818e-02, 8.95545794e-01],
       [6.87563505e-02, 8.36639008e-01, 9.46046415e-02],
       [1.08997130e-01, 3.07635489e-01, 5.83367380e-01],
       [3.78574343e-01, 2.08257319e-01, 4.13168338e-01],
       [3.14075303e-01, 1.75938154e-01, 5.09986543e-01],
       [5.14661374e-01, 1.90320746e-01, 2.95017880e-01],
       [5.97855686e-01, 3.02391035e-01, 9.97532791e-02],
       [4.20049273e-02, 3.31576489e-01, 6.26418584e-01],
       [4.86732760e-01, 1.04800924e-01, 4.08466316e-01],
       [8.01128811e-01, 3.37464192e-02, 1.65124770e-01],
       [8.98155592e-02, 6.97988466e-01, 2.12195975e-01],
       [7.29031504e-02, 8.39118736e-01, 8.79781132e-02],
       [5.10593601e-01, 2.09236547e-01, 2.80169852e-01],
       [1.24309393e-01, 7.90830108e-01, 8.48604992e-02],
       [3.42809146e-03, 3.71695

In [7]:
y_pred

array([1, 1, 0, 2, 1, 2, 2, 2, 0, 0, 2, 0, 0, 1, 1, 0, 1, 2, 0, 0, 1, 0,
       2, 1, 0, 1, 1, 0, 2, 2, 0, 1, 0, 1, 0, 2, 0, 2, 1, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 2, 1, 2, 0, 2, 2, 2, 0, 1, 1, 0, 0, 2, 0, 2, 0, 1,
       2, 1, 0, 0, 2, 2, 2, 1, 1, 2, 2, 2, 2, 2, 0, 1, 0, 1, 2, 0, 2, 2,
       1, 1, 2, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 2, 1,
       0, 1, 1, 2, 2, 2, 1, 2, 0, 0, 2, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       2, 2, 2, 2, 2, 2, 0, 2, 1, 1, 0, 1, 2, 0, 1, 0, 2, 0, 0, 1, 1, 0,
       2, 0, 1, 0, 2, 1, 2, 0, 1, 1, 0, 1, 2, 1, 0, 2, 0, 1, 1, 2, 1, 0,
       2, 1, 1, 0, 1, 0, 1, 0, 2, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 0])

In [8]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
print(confusion_matrix(y_pred,y_test))
print(accuracy_score(y_pred,y_test))
print(classification_report(y_pred,y_test))

[[56 10 17]
 [16 41  6]
 [ 3 13 38]]
0.675
              precision    recall  f1-score   support

           0       0.75      0.67      0.71        83
           1       0.64      0.65      0.65        63
           2       0.62      0.70      0.66        54

    accuracy                           0.68       200
   macro avg       0.67      0.68      0.67       200
weighted avg       0.68      0.68      0.68       200



In [9]:
from sklearn.datasets import load_iris

In [10]:
dataset=load_iris()

In [11]:
dataset

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [12]:
import pandas as pd
import numpy as np

In [13]:
df=pd.DataFrame(dataset.data,columns=dataset.feature_names)

In [14]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2