# Perceptron 

- It is a single unit of ANN. It can also be multi-layer

## Advantage:
- single layer perceptron can learn only linear seperable patterns
- Easy to implement
- Low computation power
- Perceptrons can Implement Logic gates like AND, OR.

## Disadvantage:
- Perceptron networks have several limitations.
- The output value of a perceptron can take on only one of two values( 0 or 1) due to the hard-limit activation function
- Here we just ue the step function as an activation.
- Perceptrons can only classify linear seperable sets of vectors

In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import joblib

In [25]:
class Perceptron:
    def __init__(self,eta,epochs):
        self.weights = np.random.randn(3) * 1e-4
        print("self.weights:",self.weights)
        self.eta = eta
        self.epochs = epochs

    def activationFunction(self,imputs,weights):
        z = np.dot(imputs,weights)
        return np.where(z>0,1,0)

    def fit(self,X,y):
        self.X = X
        self.y = y

        x_with_bias = np.c_[self.X, -np.ones((len(self.X),1))]
        print(f"x_with_bias: \n{x_with_bias}")

        for epoch in range(self.epochs):
            print(f"Epoch: {epoch}")
            y_hat = self.activationFunction(x_with_bias,self.weights)
            print(f"Prediction_value: \n{y_hat}")
            errors = self.y - y_hat
            print(f"errors: \n{errors}")
            self.weights = self.weights + self.eta * np.dot(x_with_bias.T,errors)
            print(f"Updated_weights: \n{self.weights}\n\n")

    def predict(self,X):
        x_with_bias = np.c_[X, -np.ones((len(X),1))]
        y_pred = self.activationFunction(x_with_bias,self.weights)
        return y_pred


## AND Operation:

In [26]:
data = {"x1": [0, 0, 1, 1], "x2": [0, 1, 0, 1], "y": [0, 0, 0, 1]}

AND = pd.DataFrame(data)
print(AND)

   x1  x2  y
0   0   0  0
1   0   1  0
2   1   0  0
3   1   1  1


In [27]:
X = AND.drop("y", axis=1)
X

x1  x2
0   0   0
1   0   1
2   1   0
3   1   1

In [28]:
y = AND["y"]
y.to_frame()

y
0  0
1  0
2  0
3  1

In [29]:
model = Perceptron(eta=0.5, epochs=10)
model.fit(X, y)

self.weights: [ 1.58769393e-06 -2.19101297e-04 -4.13842464e-05]
x_with_bias: 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
Epoch: 0
Prediction_value: 
[1 0 1 0]
errors: 
0   -1
1    0
2   -1
3    1
Name: y, dtype: int64
Updated_weights: 
[1.58769393e-06 4.99780899e-01 4.99958616e-01]


Epoch: 1
Prediction_value: 
[0 0 0 0]
errors: 
0    0
1    0
2    0
3    1
Name: y, dtype: int64
Updated_weights: 
[ 5.00001588e-01  9.99780899e-01 -4.13842464e-05]


Epoch: 2
Prediction_value: 
[1 1 1 1]
errors: 
0   -1
1   -1
2   -1
3    0
Name: y, dtype: int64
Updated_weights: 
[1.58769393e-06 4.99780899e-01 1.49995862e+00]


Epoch: 3
Prediction_value: 
[0 0 0 0]
errors: 
0    0
1    0
2    0
3    1
Name: y, dtype: int64
Updated_weights: 
[0.50000159 0.9997809  0.99995862]


Epoch: 4
Prediction_value: 
[0 0 0 1]
errors: 
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated_weights: 
[0.50000159 0.9997809  0.99995862]


Epoch: 5
Prediction_value: 
[0 0 0 1]
errors: 
0    0
1    0
2

In [30]:
model.predict(X)

array([0, 0, 0, 1])

## OR Operation

In [31]:
data = {"x1": [0, 0, 1, 1], "x2": [0, 1, 0, 1], "y": [0, 1, 1, 1]}

OR = pd.DataFrame(data)
print(OR)

   x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  1


In [32]:
X = OR.drop("y", axis=1)
X

x1  x2
0   0   0
1   0   1
2   1   0
3   1   1

In [33]:
y = OR["y"]
y.to_frame()

y
0  0
1  1
2  1
3  1

In [34]:
model = Perceptron(eta=0.5, epochs=10)
model.fit(X, y)

self.weights: [-4.40108673e-05 -1.59919388e-04 -4.49763620e-05]
x_with_bias: 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
Epoch: 0
Prediction_value: 
[1 0 1 0]
errors: 
0   -1
1    1
2    0
3    1
Name: y, dtype: int64
Updated_weights: 
[ 0.49995599  0.99984008 -0.50004498]


Epoch: 1
Prediction_value: 
[1 1 1 1]
errors: 
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
Updated_weights: 
[ 4.99955989e-01  9.99840081e-01 -4.49763620e-05]


Epoch: 2
Prediction_value: 
[1 1 1 1]
errors: 
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
Updated_weights: 
[0.49995599 0.99984008 0.49995502]


Epoch: 3
Prediction_value: 
[0 1 1 1]
errors: 
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated_weights: 
[0.49995599 0.99984008 0.49995502]


Epoch: 4
Prediction_value: 
[0 1 1 1]
errors: 
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated_weights: 
[0.49995599 0.99984008 0.49995502]


Epoch: 5
Prediction_value: 
[0 1 1 1]
errors: 
0    0
1    0
2    0
3    0
Name: y,

In [35]:
model.predict(X)

array([0, 1, 1, 1])

## XOR Operation

In [36]:
data = {"x1": [0, 0, 1, 1], "x2": [0, 1, 0, 1], "y": [0, 1, 1, 0]}
XOR = pd.DataFrame(data)
print(XOR)

   x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  0


In [37]:
X = XOR.drop("y", axis=1)
X

x1  x2
0   0   0
1   0   1
2   1   0
3   1   1

In [38]:
y = XOR["y"]
y.to_frame()

y
0  0
1  1
2  1
3  0

In [39]:
model = Perceptron(eta=0.5, epochs=100)
model.fit(X, y)

self.weights: [ 4.31692971e-05 -1.67123330e-04  1.62555150e-04]
x_with_bias: 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
Epoch: 0
Prediction_value: 
[0 0 0 0]
errors: 
0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated_weights: 
[ 0.50004317  0.49983288 -0.99983744]


Epoch: 1
Prediction_value: 
[1 1 1 1]
errors: 
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated_weights: 
[ 4.31692971e-05 -1.67123330e-04  1.62555150e-04]


Epoch: 2
Prediction_value: 
[0 0 0 0]
errors: 
0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated_weights: 
[ 0.50004317  0.49983288 -0.99983744]


Epoch: 3
Prediction_value: 
[1 1 1 1]
errors: 
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated_weights: 
[ 4.31692971e-05 -1.67123330e-04  1.62555150e-04]


Epoch: 4
Prediction_value: 
[0 0 0 0]
errors: 
0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated_weights: 
[ 0.50004317  0.49983288 -0.99983744]


Epoch: 5
Prediction_value: 
[1 1 1 1]
errors: 
0   -1
1    0
2

In [40]:
model.predict(X)

array([0, 0, 0, 0])